version: "3.7"
 
services:
    api:
        container_name: laravng_api
        build:
            context: ./../api
            dockerfile: api.dockerfile
        working_dir: /var/www
        volumes:
            - ./../api:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=homestead"
            - "DB_USERNAME=homestead"
            - "DB_PASSWORD=secret"
        networks:
            - app-network
    web:
        container_name: laravng_webserver
        build:
            context: ./../
            dockerfile: laravweb.dockerfile
        working_dir: /var/www
        volumes:
            - ./../api:/var/www
        ports:
            - "8800:80"
        networks:
            - app-network
 
    database:
        container_name: laravng_db
        image: mysql:5.6
        volumes:
            - ./../db:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
            - "33061:3306"
        networks:
            - app-network
            
    app:
        container_name: laravng_webapp
        build:
            context: ./../
            dockerfile: ngweb.dockerfile
        ports:
            - "8888:80"
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge